### ISSUE TITLE
Allow to configure a custom logging backend

### ISSUE THREAD

**Issue by marcmo** [infinyon/node-bindgen#134]
It's currently not possible to configure a custom logging backend. What is needed is a way to use a custom logger along with some guidance of where to initialize it (since we do not have a `main` where this is done for applications.

**Comment by nicholastmosher** [comment]
Thanks for the submission @marcmo! I'm going to write down some notes and observations here :)

Right now it seems that module "initialization" is somewhat static. We can see that the logging implementation [is registered here] in `init_module`, which has the `#[ctor]` attribute. I believe that this causes the init_module code to be loaded at least before any other module code, my guess is that it happens when the dynamic loader loads the shared object file.

Probably something we can think  about doing is adding some sort of hook where module authors can define their own initialization function and `init_module` can call out to it. From a user-interface perspective, it would probably be possible to create an attribute such as `#[node_bindgen(init)]` that can be used to indicate that a particular function should be used for initialization.

```rust
#[node_bindgen(init)]
fn init_my_module() {
    // Logging init or other global setup
}
```

Implementation-wise, I'm imagining that we could probably use some sort of static that holds a reference to a `Fn() -> ()` (or whatever we decide the init function signature should be) which is initialized to some empty or default init function (perhaps controlled by a feature flag), and can be overridden if a `#[node_bindgen(init)]` attribute is defined.

[is registered here]: https://github.com/infinyon/node-bindgen/blob/master/nj-core/src/module.rs#L89

**Comment by marcmo** [comment]
Hi @nicholastmosher, thanks for laying out your thoughts on this.
After reading about the `ctor` library and how it works, I seems dangerous to expose a hook so that your users can add any function.
OTOH if the initialization code fails, it will fail at startup and thus should be easy to debug.
As for how to implement a static that holds a reference to a function...I tried but failed... don't know how to implement that!
would be a nice way to enable replacing the default-logger initialization that way

**Comment by Badel2** [comment]
Hi, I also would like to setup a custom logger. The problem is that the `log` library has no way to "unset" a logger, so we are stuck with the logger from [here](https://github.com/infinyon/node-bindgen/blob/master/nj-core/src/module.rs#L89). I like the solution to add a `#[node_bindgen(init)]` attribute, but in my case I need to pass some extra arguments to that function so I would use it like this:

```
#[node_bindgen(init)]
pub fn no_init() {
    // Disable default logger
}

pub fn manual_init(args: Value) {
    // Setup logger manually, using options from args
}
```

And then just call `manual_init` manually from my code. So if this `init` attribute is hard to implement, some config option to disable the default logger would be enough for me.

**Comment by sehz** [comment]
Thanks for suggestion.  Will try to address this issue soon.

**Comment by sehz** [comment]
@Badel2  What option do you need for init?  It's hard to pass argument.  It would be simpler if pick up form env variable.

If we go with `init` attribute. then it just matter of copy/paste function in the init_module

**Comment by Badel2** [comment]
Actually I need to pass a function, like this:

```js
let rust_addon = require("../../rust-dist");
rust_addon.manual_init(function(msg) {
    console.log(msg);
});
```

I tried to get a reference to `console.log` using `JsEnv`, but that didn't work.

Another possibility is to allow using `RUST_LOG=off` to disable the default logger, you would need to modify this function:

https://github.com/infinyon/node-bindgen/blob/6450525dbd3202310b1e153adb1314062842477c/nj-core/src/lib.rs#L124-L126

Into something like

```rust
if std::env("RUST_LOG") == "off" {
    // Do not initialize logger here, to allow user to set a custom logger
} else {
    fluvio_future::subscriber::init_logger(); 
}
```

**Comment by sehz** [comment]
Thanks to @marcmo, this issue is resolved.   Should do release? I think only minor bump version is necessary
