### ISSUE TITLE
Support for electronjs applications with node-bindgen

### ISSUE THREAD

**Issue by JakubGawron23** [infinyon/node-bindgen#167]
I'm curious to see how the electron app support works. At what stage are they?
Was it possible to rewrite this one c++ file to Rust ?

**Comment by sehz** [comment]
I believe electron app is working as you can the example here: https://github.com/infinyon/node-bindgen/tree/master/examples/electron.   Have you tried?

**Comment by Badel2** [comment]
I can confirm that electron support works pretty well, in both windows and linux. Just make sure that you are compiling the rust module using `npx electron-build-env nj-cli build --release`, otherwise you can get error "A dynamic link library (DLL) initialization routine failed" when importing the rust module in electron. I missed this detail in my electron app and it was very hard to debug, I think you should add it to the README.

**Comment by sehz** [comment]
Definitely,  thanks for confirmation.

**Comment by sehz** [comment]
add to README.  closing issue
