### ISSUE TITLE
Replace nj-cli build with build.rs script?

### ISSUE THREAD

**Issue by timfish** [infinyon/node-bindgen#48]
I noticed that all `nj-cli` currently does is call `cargo build` and then copy and rename the output library. As far as I can work out, it also currently only copies the [debug output](https://github.com/infinyon/node-bindgen/blob/1e4e9f9d652a40ded0af8781cb371f19f2fc2860/nj-cli/src/main.rs#L68).

Currently I cannot use `nj-cli` to build `--release` or for any other arch/platform/toolchain because it calls `cargo build` for me.

Would it be better if the copy/rename output was as a function that users called from their `build.rs`? That way users could call `cargo build --release --whatever-else`  and it would work the same as `nj-cli.

**Comment by sehz** [comment]
Yes, you are right, nj-cli is just wrapper around ```cargo build```.   It just way to make easier to get build going.   Need to update doc  to indicate it is optional and example of using ```build.rs`` to build.

**Comment by timfish** [comment]
Ahhh, I had forgotten that `build.rs` is not able to do post build tasks so it will no be able to replace `nj-cli`. 

I would be good however if `nj-cli` could pass all arguments to cargo!

**Comment by sehz** [comment]
I agree

**Comment by nicholastmosher** [comment]
So I've investigated this a little bit and it seems to be easy to do if you don't mind adding the `--` before the arguments you want to forward. For example, it'd be easy to make this work:

```
nj-cli build -- --release
```

But I so far have not found a way (using structopt or clap) to do this:

```
nj-cli build --release
```

I have a prototype written to accomplish the `--` case, I can push that to a PR if you're interested in seeing. Otherwise, I wonder if anybody has more ideas about how to go about this.

**Comment by sehz** [comment]
Please open PR with using ```--``` way to pass rest of arguments to cargo build.

**Comment by sehz** [comment]
release flag is added to build command:
```
nj-cli build --release
```
